coverage:
  notify:
    slack:
      default:
        url: secret:Ha+dbdiMCGOdxb3WxyaNeTsri1ELOUsyccZ3OlQhQVkAp3upVUAypZQjXkZXfWzdgma8kSPoeAoSvzp5MOFzK0Iy4sTKB7y38x4KlZ8u/kBh/yzQJCJEkHeq/oGgAwtzazTH4wPURMm8Fx5mONIU2I2F21/OWuYOPv3FJmFNNPA=
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null